config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'articles#index', as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new', as: :unauthenticated_root
  end

  get '/articles_list', to: 'articles#articles_list', as: 'articles_list', defaults: { format: :turbo_stream }

  resources :articles do
    resources :likes, only: [:create]
    resources :comments do
      resources :likes, only: [:create]
    end
  end

  resources :comments do
    resources :comments do
      resources :likes, only: [:create]
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :crop_x, :crop_y, :crop_width, :crop_height

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :image, presence: true

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image

  after_commit :crop_image, if: :should_crop_image?

  private

  def should_crop_image?
    image.attached? && crop_x.present? && crop_y.present? && crop_width.present? && crop_height.present? && !@image_processing
  end

  def crop_image
    @image_processing = true

    blob = image.blob

    image_path = ActiveStorage::Blob.service.send(:path_for, blob.key)
    processed_image = MiniMagick::Image.open(image_path)

    processed_image.crop "#{crop_width}x#{crop_height}+#{crop_x}+#{crop_y}"

    processed_image_io = StringIO.new
    processed_image.write(processed_image_io)
    processed_image_io.rewind

    image.attach(io: processed_image_io,
                 filename: blob.filename,
                 content_type: blob.content_type)

    @image_processing = false
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models

  has_many :articles
  has_many :likes
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :pundishing_user

  private

  def pundishing_user
    flash[:notice] = 'You are not authorized to perform this action.'
    redirect_to article_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles, only: %i[index articles_list]
  before_action :set_article, only: %i[show edit update destroy]

  def index
    respond_to do |format|
      format.html
    end
  end

  def articles_list; end

  def show; end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = current_user.articles.new(article_params)
    authorize @article
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    authorize @article

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @article
    @article.destroy

    redirect_to authenticated_root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :image, :crop_x, :crop_y, :crop_width, :crop_height)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def set_articles
    @articles = Article.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  before_action :set_commentable, only: [:destroy]
  before_action :set_article_id, only: [:create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment

    @comment.save

    redirect_to article_path(@article_id)
  end

  def destroy
    @comment.destroy

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :article_id)
  end

  def find_commentable
    if params[:article_id]
      @commentable = Article.find(params[:article_id])
    elsif params[:comment_id]
      @commentable = Comment.find(params[:comment_id])
    end
  end

  def set_commentable
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])
  end

  def set_article_id
    @article_id = params[:comment][:article_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_likeable, only: [:create]

  def create
    @like = @likeable.likes.find_or_initialize_by(user: current_user)
    @like.save if @like.new_record?

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def find_likeable
    if params[:article_id]
      @likeable = Article.find(params[:article_id])
    elsif params[:comment_id]
      @likeable = Comment.find(params[:comment_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_placeholder.html.erb
<div class="w-full">
  <div class="w-full h-64 bg-gray-300 rounded-lg dark:bg-gray-600">
    <h1 class="w-56 h-2 mt-4 bg-gray-200 rounded-lg dark:bg-gray-700"></h1>
  </div>
</div>

app/views/articles/_articles_placeholder.html.erb
<div class="w-full">
  <div class="w-full h-64 bg-gray-300 rounded-lg dark:bg-gray-600">
    <h1 class="w-56 h-2 mt-4 bg-gray-200 rounded-lg dark:bg-gray-700"></h1>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container py-5">
  <div class="flex space-x-4 font-sans font-bold text-base justify-content-end">
    <%=
      link_to 'Back',
              authenticated_root_path,
              class: 'text-decoration-none text-black'
    %>
    <%=
      button_to 'Sign out',
                destroy_user_session_path,
                method: :delete,
                class: 'text-decoration-none text-black'
    %>
  </div>

  <div class="py-5">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="d-flex justify-content-center">
          <div class="bg-gray-600 rounded-md shadow-lg p-5 w-full">
            <%= form_with model: article do |form| %>
              <div data-controller="image-cropping" class="mt-2">
                <div class="mt-2">
                  <%=
                    form.label :title,
                               class: 'form-label text-base font-sans font-bold'
                  %><br>
                  <%=
                    form.text_field :title,
                                    class: 'form-control',
                                    placeholder: 'Title'
                  %>
                  <% article.errors.full_messages_for(:title).each do |message| %>
                    <div class="error-message"><%= message %></div>
                  <% end %>
                </div>

                <div class="mt-4">
                  <%=
                    form.label :Description,
                               class: 'form-label text-base font-sans font-bold'
                  %><br>
                  <%=
                    form.text_area :body,
                                   class: 'form-control',
                                   placeholder: 'Tell your story...',
                                   rows: 6
                  %>
                  <br>
                  <% article.errors.full_messages_for(:body).each do |message| %>
                    <div class="error-message"><%= message %></div>
                  <% end %>
                </div>

                <div>
                  <%=
                    form.label :image,
                               style: 'display: block',
                               class: 'text-base font-sans font-bold pb-2'
                  %>
                  <%=
                    form.file_field :image,
                                    data: {
                                      action:
                                        'change->image-cropping#imageSelected'
                                    }
                  %>

                  <div class="mt-3 ">
                    <%=
                      image_tag '',
                                data: {
                                  image_cropping_target: 'image'
                                },
                                style: 'max-width: 100%; display: none;',
                                class: 'w-50 h-50'
                    %>
                  </div>

                  <%=
                    form.hidden_field :crop_x,
                                      data: {
                                        image_cropping_target: 'x'
                                      }
                  %>
                  <%=
                    form.hidden_field :crop_y,
                                      data: {
                                        image_cropping_target: 'y'
                                      }
                  %>
                  <%=
                    form.hidden_field :crop_width,
                                      data: {
                                        image_cropping_target: 'width'
                                      }
                  %>
                  <%=
                    form.hidden_field :crop_height,
                                      data: {
                                        image_cropping_target: 'height'
                                      }
                  %>
                </div>
                <div class="flex justify-content-end">
                  <%=
                    form.submit 'Publish',
                                class:
                                  'rounded-md bg-green-100 text-decoration-none py-2 px-4 text-center text-white hover:bg-green-300 mt-2 text-sm shadow-md'
                  %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/article_list.turbo_stream.erb
<%= turbo_stream.remove("article_placeholder") %>

<%= turbo_stream.append("articlelist") do %>
  <div class=" container flex flex-wrap gap-6 pb-4 justify-center">
    <% @articles.each do |article| %>
      <div class="cursor-pointer group relative flex flex-col bg-white shadow-sm border border-slate-200 rounded-lg w-72 hover:shadow-lg transition-shadow duration-300">
        <div class="relative h-56 mx-2.5 mt-2.5 mb-0 overflow-hidden text-white rounded-md">
          <%= image_tag (article.image), alt: 'My Logo', class:"transition-transform duration-500 ease-[cubic-bezier(0.25, 1, 0.5, 1)] transform group-hover:scale-110" if  article.image.attached? %>
        </div>

        <div class="px-4 pb-5 -mt-10">
          <h6 class="mb-2 text-slate-800 text-xl font-semibold">
            <%= truncate(article.title, length: 26) %>
          </h6>
          <p class="text-slate-600 leading-normal break-words font-light">
            <%= truncate(article.body, length: 60) %>
          </p>
        </div>

        <div class="absolute bottom-0 left-0 right-0 px-4 pb-4">
          <a class="rounded-md bg-green-100 text-decoration-none py-2 px-4 text-center text-white hover:bg-green-300 mt-2 text-sm shadow-md" href="/articles/<%= article.id %>" data-turbo-frame="_top">
            Read article
          </a>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @articles.next_page %>
  <%= turbo_stream.replace "articles_pagination" do %>
    <%= turbo_frame_tag "articles_pagination", src: article_list_path(page: @articles.next_page), loading: :lazy do %>
      <section class="bg-white dark:bg-gray-900" id="article_placeholder">
          <div class="container px-6 py-10 mx-auto animate-pulse">
              <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-3">
                <% for a in 1..8 do %>
                  <%= render "article_placeholder" %>
                <% end %>
              </div>
          </div>
      </section>
    <% end %>
  <% end %>
<% end %>

app/views/articles/articlelist.turbo_stream.erb
<%= turbo_stream.remove("article_placeholder") %>

<%= turbo_stream.append("articlelist") do %>
  <div class=" container flex flex-wrap gap-6 pb-4 justify-center">
    <% @articles.each do |article| %>
      <div class="cursor-pointer group relative flex flex-col bg-white shadow-sm border border-slate-200 rounded-lg w-72 hover:shadow-lg transition-shadow duration-300">
        <div class="relative h-56 mx-2.5 mt-2.5 mb-0 overflow-hidden text-white rounded-md">
          <%= image_tag (article.image), alt: 'My Logo', class:"transition-transform duration-500 ease-[cubic-bezier(0.25, 1, 0.5, 1)] transform group-hover:scale-110" if  article.image.attached? %>
        </div>

        <div class="px-4 pb-5 -mt-10">
          <h6 class="mb-2 text-slate-800 text-xl font-semibold">
            <%= truncate(article.title, length: 26) %>
          </h6>
          <p class="text-slate-600 leading-normal break-words font-light">
            <%= truncate(article.body, length: 60) %>
          </p>
        </div>

        <div class="absolute bottom-0 left-0 right-0 px-4 pb-4">
          <a class="rounded-md bg-green-100 text-decoration-none py-2 px-4 text-center text-white hover:bg-green-300 mt-2 text-sm shadow-md" href="/articles/<%= article.id %>" data-turbo-frame="_top">
            Read article
          </a>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @articles.next_page %>
  <%= turbo_stream.replace "articles_pagination" do %>
    <%= turbo_frame_tag "articles_pagination", src: articlelist_path(page: @articles.next_page), loading: :lazy do %>
      <section class="bg-white dark:bg-gray-900" id="article_placeholder">
          <div class="container px-6 py-10 mx-auto animate-pulse">
              <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-3">
                <% for a in 1..8 do %>
                  <%= render "article_placeholder" %>
                <% end %>
              </div>
          </div>
      </section>
    <% end %>
  <% end %>
<% end %>

app/views/articles/articles_list.turbo_stream.erb
<%= turbo_stream.remove("articles_placeholder") %>

<%= turbo_stream.append("articlelist") do %>
  <div class=" container flex flex-wrap gap-6 pb-4 justify-center">
    <% @articles.each do |article| %>
      <div class="cursor-pointer group relative flex flex-col bg-white shadow-sm border border-slate-200 rounded-lg w-72 hover:shadow-lg transition-shadow duration-300">
        <div class="relative h-56 mx-2.5 mt-2.5 mb-0 overflow-hidden text-white rounded-md">
          <%= image_tag (article.image), alt: 'My Logo', class:"transition-transform duration-500 ease-[cubic-bezier(0.25, 1, 0.5, 1)] transform group-hover:scale-110" if  article.image.attached? %>
        </div>

        <div class="px-4 pb-5 -mt-10">
          <h6 class="mb-2 text-slate-800 text-xl font-semibold">
            <%= truncate(article.title, length: 26) %>
          </h6>
          <p class="text-slate-600 leading-normal break-words font-light">
            <%= truncate(article.body, length: 60) %>
          </p>
        </div>

        <div class="absolute bottom-0 left-0 right-0 px-4 pb-4">
          <a class="rounded-md bg-green-100 text-decoration-none py-2 px-4 text-center text-white hover:bg-green-300 mt-2 text-sm shadow-md" href="/articles/<%= article.id %>" data-turbo-frame="_top">
            Read article
          </a>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @articles.next_page %>
  <%= turbo_stream.replace "articles_pagination" do %>
    <%= turbo_frame_tag "articles_pagination", src: articles_list_path(page: @articles.next_page), loading: :lazy do %>
      <section class="bg-white dark:bg-gray-900" id="articles_placeholder">
          <div class="container px-6 py-10 mx-auto animate-pulse">
              <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-3">
                <% for a in 1..8 do %>
                  <%= render "articles_placeholder" %>
                <% end %>
              </div>
          </div>
      </section>
    <% end %>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <div class="container py-5">
    <div class="d-flex justify-between pb-5">
      <div class="flex space-x-4 px-2 font-sans font-bold text-base pt-2">
        <%=
          link_to 'Home',
                  authenticated_root_path,
                  class: 'text-decoration-none text-black'
        %>
      </div>

      <div>
        <p class="text-3xl font-bold text-green-100">Bloggy</p>
      </div>

      <div class="flex space-x-4 px-2 font-sans font-bold text-base pt-2">
        <%=
          link_to 'Write',
                  new_article_path,
                  class: 'text-decoration-none text-black'
        %>
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
      </div>
    </div>

    <%= turbo_frame_tag :articlelist, src: articles_list_path(page: @articles.current_page), loading: :lazy do %>
      <section class="bg-white dark:bg-gray-900" id="articles_placeholder">
        <div class="container px-6 py-10 mx-auto animate-pulse">
          <div
            class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-3">
            <% for a in 1..8 do %>
              <%= render 'articles_placeholder' %>
            <% end %>
          </div>
        </div>
      </section>
    <% end %>

    <%= turbo_frame_tag 'articles_pagination' %>
  </div>
<% else %>
  <%=
    button_to 'Sign in',
              unauthenticated_root_path,
              class: 'btn btn-outline-success'
  %>
<% end %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<% if user_signed_in? %>
  <div class="container py-5">
    <div class="d-flex justify-between mb-3">
      <div>
        <%=
          link_to 'Back',
                  authenticated_root_path,
                  class:
                    'font-sans font-bold text-base text-decoration-none text-black'
        %>
      </div>

      <div class="flex justify-content-end">
        <% if policy(@article).update? %>
          <%= link_to edit_article_path(@article), class: "btn" do %>
            <%= image_tag 'edit.svg', alt: 'Edit', width: 25, height: 25 %>
          <% end %>
        <% end %>

        <% if policy(@article).destroy? %>
          <%= link_to  article_path(@article),class: "btn", data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
      } do %>
            <%= image_tag 'delete.svg', alt: 'Delete', width: 25, height: 25 %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div>
      <div class="d-flex justify-content-center p-5">
        <div>
          <h1 class="px-5 flex items-center"><%= @article.title %></h1>
          <small class="text-sm text-muted px-5"><%=
              time_ago_in_words(@article.created_at)
                                                 %>
            ago</small>
        </div>
        <%=
          image_tag (@article.image),
                    alt: 'My Logo',
                    width: 500,
                    height: 500,
                    class: 'rounded-lg mr-2'
        %>
      </div>

      <%= turbo_frame_tag "comment" do %>
        <div class="px-5">
          <p class="text-xl d-flex justify-content-center">
            <%= @article.body %>
          </p>
          <div class="d-flex mb-3 border-top border-bottom">
            <div class="p-2">
              <%= button_to article_likes_path(@article), class: "btn" do %>
                <%= turbo_frame_tag "clap-#{@article.id}" do %>
                  <% if @article.likes.exists?(user_id: current_user.id) %>
                    <%=
                      image_tag 'clap-filled.svg',
                                alt: 'Liked',
                                width: 20,
                                height: 20
                    %>
                  <% else %>
                    <%=
                      image_tag 'clap.svg', alt: 'Clap', width: 20, height: 20
                    %>
                  <% end %>
                  <%= @article.likes.count %>
                <% end %>
              <% end %>
            </div>

            <div class="p-2">
              <%= link_to  @article, class: "btn" do %>
                <%=
                  image_tag 'message.svg', alt: 'Reply', width: 20, height: 20
                %>
                <%= @article.comments.count %>
              <% end %>
            </div>
          </div>

          <div class="pt-3">
            <ul>
              <h6>Responses(<%= @article.comments.count %>)</h6>

              <div class="bg-gray-600 rounded-lg shadow-md p-4 w-75">
                <%= form_with model: [@article, Comment.new] do |f| %>
                  <%=
                    f.text_area :body,
                                placeholder: 'What are your thoughts?',
                                class:
                                  'bg-gray-600 text-sm border-none p-3 w-100'
                  %><br>
                  <%= f.hidden_field :article_id, value: @article.id %>
                  <div class="d-flex justify-content-end mt-1">
                    <%=
                      f.submit 'Respond',
                               class:
                                 'rounded-md bg-green-100 text-decoration-none py-2 px-4 text-center text-white hover:bg-green-300 text-sm shadow-md'
                    %>
                  </div>
                <% end %>
              </div>

              <ul>
                <%= render @article.comments, article: @article %>
              </ul>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <%= button_to 'Sign in', unauthenticated_root_path %>
<% end %>

app/views/comments/_comment.html.erb
<div class="border-top mt-3">
  <div class="mt-2">
    <small class="small-text text-muted"><%=
        time_ago_in_words(comment.created_at)
                                         %>
      ago
    </small>
    <br>

    <%= comment.body %>

    <div class="d-flex">
      <%= button_to comment_comment_likes_path(comment.commentable, comment), method: :post, class: "btn" do %>
        <%= turbo_frame_tag "clap-#{comment.id}" do %>
          <% if comment.likes.exists?(user_id: current_user.id) %>
            <%=
              image_tag 'clap-filled.svg', alt: 'liked', width: 20, height: 20
            %>
          <% else %>
            <%= image_tag 'clap.svg', alt: 'not-liked', width: 20, height: 20 %>
          <% end %>
          <%= comment.likes.count %>
        <% end %>
      <% end %>

      <%= link_to  @article, class: "btn"  do %>
        <%= image_tag 'message.svg', alt: 'reply', width: 20, height: 20 %>
        <%= comment.comments.count %>
      <% end %>

      <% if policy(comment).destroy? %>
        <%= link_to  comment_path(comment, article_id: @article.id),class: "btn", data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } do %>
          <%= image_tag 'delete.svg', alt: 'Delete', width: 20, height: 20 %>
        <% end %>
      <% end %>
    </div>

    <div class="bg-gray-600 rounded-lg shadow-md p-3 w-75">
      <%= form_with model: [comment, Comment.new] do |f| %>
        <%=
          f.text_area :body,
                      placeholder: 'Replying to...',
                      class: 'bg-gray-600 text-sm border-none p-3 w-100'
        %>
        <%= f.hidden_field :article_id, value: @article.id %>
        <br>
        <div class=" d-flex justify-content-end mt-1 ">
          <%=
            f.submit 'Respond',
                     class:
                       'rounded-md bg-green-100 text-decoration-none py-2 px-4 text-center text-white hover:bg-green-300 text-sm shadow-md'
          %>
        </div>
      <% end %>
    </div>

    <ul>
      <%= render comment.comments %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-600">
    <%= yield %>
  </body>
</html>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace "clap-#{@likeable.id}" do %>
  <%= image_tag "clap-filled.svg", alt: "Edit", width: 20, height: 20 %>
  <span><%= @likeable.likes.count %></span>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <span class="d-flex justify-content-center pt-3 " style="font-size: 12px;">
    Already have an account? &nbsp; <%= link_to "Log in", new_session_path(resource_name) %>
  </span>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <span class="d-flex justify-content-center pt-3 " style="font-size: 12px;">
    Don't have an account? &nbsp; <%= link_to "Sign up", new_registration_path(resource_name) %>
  </span>
<% end %>
 
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <span class="d-flex justify-content-center pt-2" style="font-size: 11px;">
    <%= link_to "Forgot your password?", new_password_path(resource_name) %>
  </span><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>